### ISSUE TITLE
Is there any Support for attributeNodes for Dynamic Entity Graphs?

### ISSUE THREAD

**Issue by krisiye** [Cosium/spring-data-jpa-entity-graph#71] opened 2022-07-19 18:56 UTC
Similar to attributePaths (EntityGraphUtils.fromAttributePaths), is there any support for dynamically adding attribute nodes? At the moment under my use-case I am able to use Dynamic Entity Graphs based on my request (graphql)  and select the right set of EntityGraphs to load which is great. However, we end up loading all columns on the entity when the request really only needs a few. Although graphql optimizes this by only sending back what we ask for over the wire, It would also be nice to only ask for what we need from the database as opposed to all attributes on an Entity. 

I know I can do that with NamedEntityGraphs by adding attribute Nodes along with the Fetch strategy.  Wondering if there is a similar mechanism to achieve the same results with Dynamic Entity Graphs. 

Appreciate your feedback!

**Comment by reda-alaoui** [comment] 2022-07-19 18:58
Looks like a duplicate of #24

**Closed** 2022-07-19 18:59 UTC
